Utilizaremos el files_for_lab/customer_churn.csv conjunto de datos para construir un predictor de abandono.

In [2]:
import pandas as pd
df = pd.read_csv (r"C:\Users\usuario\Desktop\Bootcamp-Ironhack\Ejercicios Clase\Semana 9 (30.04)\Dia 1 (Unidad 3)\Customer_Churn.csv")

1. Cargue el conjunto de datos y explore las variables.

In [6]:
df

customerID  gender  SeniorCitizen Partner Dependents  tenure  \
0     7590-VHVEG  Female              0     Yes         No       1   
1     5575-GNVDE    Male              0      No         No      34   
2     3668-QPYBK    Male              0      No         No       2   
3     7795-CFOCW    Male              0      No         No      45   
4     9237-HQITU  Female              0      No         No       2   
...          ...     ...            ...     ...        ...     ...   
7038  6840-RESVB    Male              0     Yes        Yes      24   
7039  2234-XADUH  Female              0     Yes        Yes      72   
7040  4801-JZAZL  Female              0     Yes        Yes      11   
7041  8361-LTMKD    Male              1     Yes         No       4   
7042  3186-AJIEK    Male              0      No         No      66   

     PhoneService     MultipleLines InternetService OnlineSecurity  ...  \
0              No  No phone service             DSL             No  ...   
1             Yes                No             DSL            Yes  ...   
2             Yes                No             DSL            Yes  ...   
3              No  No phone service             DSL            Yes  ...   
4             Yes                No     Fiber optic             No  ...   
...           ...               ...             ...            ...  ...   
7038          Yes               Yes             DSL            Yes  ...   
7039          Yes               Yes     Fiber optic             No  ...   
7040           No  No phone service             DSL            Yes  ...   
7041          Yes               Yes     Fiber optic             No  ...   
7042          Yes                No     Fiber optic            Yes  ...   

     DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0                  No          No          No              No  Month-to-month   
1                 Yes          No          No              No        One year   
2                  No          No          No              No  Month-to-month   
3                 Yes         Yes          No              No        One year   
4                  No          No          No              No  Month-to-month   
...               ...         ...         ...             ...             ...   
7038              Yes         Yes         Yes             Yes        One year   
7039              Yes          No         Yes             Yes        One year   
7040               No          No          No              No  Month-to-month   
7041               No          No          No              No  Month-to-month   
7042              Yes         Yes         Yes             Yes        Two year   

     PaperlessBilling              PaymentMethod MonthlyCharges  TotalCharges  \
0                 Yes           Electronic check          29.85         29.85   
1                  No               Mailed check          56.95        1889.5   
2                 Yes               Mailed check          53.85        108.15   
3                  No  Bank transfer (automatic)          42.30       1840.75   
4                 Yes           Electronic check          70.70        151.65   
...               ...                        ...            ...           ...   
7038              Yes               Mailed check          84.80        1990.5   
7039              Yes    Credit card (automatic)         103.20        7362.9   
7040              Yes           Electronic check          29.60        346.45   
7041              Yes               Mailed check          74.40         306.6   
7042              Yes  Bank transfer (automatic)         105.65        6844.5   

     Churn  
0       No  
1       No  
2      Yes  
3       No  
4      Yes  
...    ...  
7038    No  
7039    No  
7040    No  
7041   Yes  
7042    No  

[7043 rows x 21 columns]

2. Intentaremos predecir la variable Churn utilizando una regresión logística sobre las variables tenure, Senior_Citizen, Monthly_Charges.

In [9]:
# Paso 1: Importar las bibliotecas necesarias
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [8]:
# Paso 3: Preparar los datos, Seleccionamos las columnas relevantes y preprocesamos los datos según sea necesario.
# Convertir la variable Churn a binaria
df['Churn'] = df['Churn'].apply(lambda x: 1 if x == 'Yes' else 0)

# Seleccionar las columnas necesarias
X = df[['tenure', 'SeniorCitizen', 'MonthlyCharges']]
y = df['Churn']


In [10]:
# Paso 4: Dividir los datos en conjuntos de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [11]:
# Paso 5: Entrenar el modelo de regresión logística.
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [12]:
# Paso 6: Realizar predicciones y evaluar el modelo.
# Predicciones
y_pred = model.predict(X_test)

# Evaluar el modelo
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print(f'Accuracy: {accuracy}')
print('Confusion Matrix:')
print(conf_matrix)
print('Classification Report:')
print(class_report)

Accuracy: 0.7936583057264552
Confusion Matrix:
[[1420  119]
 [ 317  257]]
Classification Report:
              precision    recall  f1-score   support

           0       0.82      0.92      0.87      1539
           1       0.68      0.45      0.54       574

    accuracy                           0.79      2113
   macro avg       0.75      0.69      0.70      2113
weighted avg       0.78      0.79      0.78      2113



3. Extraer la variable de destino.

In [13]:
# Paso 1: Preprocesar la variable de destino, Convierte la variable Churn a un formato binario (0 o 1):
df['Churn'] = df['Churn'].apply(lambda x: 1 if x == 'Yes' else 0)

In [15]:
# Paso 2: Extraer la variable de destino y las variables independientes, Extraemos Churn como la variable de destino y tenure, SeniorCitizen, MonthlyCharges como variables independientes:
# Variables independientes
X = df[['tenure', 'SeniorCitizen', 'MonthlyCharges']]

# Variable de destino
y = df['Churn']

print("Variables independientes (X):")
print(X.head())

print("\nVariable de destino (y):")
print(y.head())

Variables independientes (X):
   tenure  SeniorCitizen  MonthlyCharges
0       1              0           29.85
1      34              0           56.95
2       2              0           53.85
3      45              0           42.30
4       2              0           70.70

Variable de destino (y):
0    0
1    0
2    0
3    0
4    0
Name: Churn, dtype: int64


4. Extraer las variables independientes y escalarlas.

In [16]:
from sklearn.preprocessing import StandardScaler

In [22]:
df['Churn'] = df['Churn'].apply(lambda x: 1 if x == 'Yes' else 0)

In [23]:
# Paso 1: Extraer las variables independientes y la variable de destino
# Variables independientes
X = df[['tenure', 'SeniorCitizen', 'MonthlyCharges']]

# Variable de destino
y = df['Churn']

In [24]:
# Paso 2: Escalar las variables independientes.
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)


In [25]:
# Paso 3: Verificar los Escalados.
print("Variables independientes escaladas (X_scaled):")
print(X_scaled[:5])

print("\nVariable de destino (y):")
print(y.head())

Variables independientes escaladas (X_scaled):
[[-1.27744458 -0.43991649 -1.16032292]
 [ 0.06632742 -0.43991649 -0.25962894]
 [-1.23672422 -0.43991649 -0.36266036]
 [ 0.51425142 -0.43991649 -0.74653546]
 [-1.23672422 -0.43991649  0.19736523]]

Variable de destino (y):
0    0
1    0
2    0
3    0
4    0
Name: Churn, dtype: int64
